# Description:
# Generated model and runtime code.
#
package(
    default_visibility = ["//visibility:public"],
)

cc_library(
  name = "generated_libhello",
  srcs = glob(["lib/*"]),
  linkstatic = 1,
  visibility = ["//visibility:public"],
)
